# -*- coding: utf-8 -*-
"""2_Saved_Scholarships.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyNCxpHUBPZuAwMqStQr5bHqqGXZy6yv
"""

import streamlit as st

st.title("💾 Saved Scholarships")

st.info("Feature coming soon: You'll be able to save your favorite scholarships into a personal list! 📋")

st.markdown("---")
st.markdown("✅ Stay tuned! Future updates will allow you to:")
st.markdown("- Save scholarships during search")
st.markdown("- Track application deadlines")
st.markdown("- Manage your application checklist")