# -*- coding: utf-8 -*-
"""2_Saved_Scholarships.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyNCxpHUBPZuAwMqStQr5bHqqGXZy6yv
"""

import streamlit as st
import pandas as pd

# --- Page Settings ---
st.set_page_config(page_title="Saved Scholarships", page_icon="💾", layout="wide")

# --- Title ---
st.title("💾 Saved Scholarships")

# --- Load Saved Scholarships ---
try:
    saved_df = pd.read_csv("saved_scholarships.csv")
    if not saved_df.empty:
        st.dataframe(saved_df, use_container_width=True)

        st.success(f"✅ You have saved {len(saved_df)} scholarships.")
    else:
        st.info("📭 No scholarships saved yet. Go back to search and save some!")
except FileNotFoundError:
    st.info("📭 No scholarships saved yet. Go back to search and save some!")

# --- Footer ---
st.markdown("---")
st.caption("Created by Dr.K | Scholarship Search - Accounting 2025 🎯")