# -*- coding: utf-8 -*-
"""3_Scholarship_Tips.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GsvadGRYFxXnNbrHyIwkiEdv_KGxT6L
"""

import streamlit as st

st.title("📚 Scholarship Application Tips")

st.markdown("""
### ✨ Top Tips for Winning Scholarships:
- **Start Early**: Application deadlines sneak up fast!
- **Personalize Your Essay**: Tailor every essay to the specific scholarship.
- **Get Strong Recommendations**: Ask professors early.
- **Highlight Leadership and Community Involvement**: They love to see impact!
- **Double-Check Requirements**: Small mistakes cost awards.
- **Apply to MANY**: Don't just pick one!

---
""")

st.success("Believe in yourself! Every application gets you closer to free tuition 🎯")