# -*- coding: utf-8 -*-
"""3_Scholarship_Tips.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GsvadGRYFxXnNbrHyIwkiEdv_KGxT6L
"""

import streamlit as st

# --- Page Settings ---
st.set_page_config(page_title="Scholarship Tips", page_icon="💡", layout="wide")

# --- Title ---
st.title("💡 Scholarship Tips for Students")

# --- Content ---
st.markdown("""
## 📚 Best Practices for Winning Scholarships:

- **Start Early**: Deadlines come faster than you expect. Plan months ahead!
- **Customize Essays**: Tailor each application to match the scholarship mission.
- **Highlight Achievements**: Leadership, community service, and academic awards are key!
- **Ask for Strong Recommendations**: Choose teachers or mentors who know you well.
- **Proofread Carefully**: Typos can cost you opportunities.
- **Apply Widely**: Increase your chances by applying to many scholarships.

---
## 📍 Special Tips for Accounting Scholarships:

- Emphasize your interest in **financial literacy** and **ethical responsibility**.
- Mention **CPA aspirations** or **finance career goals**.
- Look for local **state accounting societies** — many offer scholarships.
- Highlight **internships or part-time jobs** related to finance/accounting fields.

---
""")

# --- Footer ---
st.markdown("---")
st.caption("Created by Dr.K | Scholarship Search - Accounting 2025 🎯")